version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: nestjs-amazon-clone-mongodb
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
